apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackhub-ingress
  annotations:
    # Questa annotazione è magica per K3s/Traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hackhub-frontend
            port:
              number: 80