# Service Kubernetes per esporre il frontend Angular di HackHub all'interno del cluster
apiVersion: v1
kind: Service
metadata:
  name: hackhub-frontend
spec:
  selector:
    app: hackhub-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80