apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackhub-ingress
  annotations:
    # Forza l'uso dell'entrypoint HTTP (web)
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hackhub-frontend
            port:
              number: 80