services:
  hackhub-back:
    environment:
      - HACKHUB_APP_JWTSECRETBASE64=${HACKHUB_APP_JWTSECRETBASE64}

  postgres:
    image: postgres:15-alpine
    container_name: hackhub-db
    environment:
      POSTGRES_DB: hackhub_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: