spring.application.name=HackhubBack

## Configurazione PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hackhub_db
spring.datasource.username=postgres
spring.datasource.password=SassoRosso
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update

# JWT key (deve essere lunga almeno 32 caratteri per HS256)
hackhub.app.jwtSecret=fhgbwiwe7rh9qutbgw'r9ugb9'w734sdfsft4yfhrhq3bituwrgbruog-ffklsjiej&%$hdjd



# Per vedere le query SQL nella console (utile per debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Log
logging.level.com.hackhub=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.hackhub.hackhubback.security=DEBUG