spring.application.name=HackhubBack

## Configurazione PostgreSQL
spring.sql.init.mode=always
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/DB_Name}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

# JWT key: preferiamo usare una chiave base64 via env var JWT_SECRET_BASE64
spring.security.jwt.secret-base64=${HACKHUB_APP_JWTSECRETBASE64:}


# Per vedere le query SQL nella console (utile per debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Log
logging.level.com.hackhub=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.hackhub.hackhubback.security=DEBUG