# PersistentVolumeClaim per allocare spazio disco (1Gi, gibibyte) per i dati di Postgres nel cluster Kubernetes
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi